# Generated by Django 4.0.2 on 2022-07-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='place',
        ),
    ]
