# Generated by Django 4.0.2 on 2022-07-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('comments', '0002_remove_comment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
