# Generated by Django 4.0.2 on 2022-08-02 01:43

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=places.models.upload_load),
        ),
    ]
